### ISSUE TITLE
find another database

### ISSUE THREAD

**Issue by laurentperrinet** [bicv/SparseHebbianLearning#13]
We need to find a more generic and large database than ``serre07_*`` or ``kodakdb`` - we should use that databases that are provided by machine learning , for instance:

 * STL10: http://pytorch.org/docs/master/torchvision/datasets.html#stl10 

may be we should include some part of the https://github.com/mttk/STL10/blob/master/stl10_input.py file into our scripts ?

best would be even more generic images from instagram etc...

**Comment by slike04** [comment]
Yep, I was thinking the same, it would certainly bring more robust results
